name: CI/CD pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  BUILD_ARTIFACT_NAME: "package"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache pnpm dependencies
        uses: actions/cache@v2
        id: cache-pnpm
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: |
          pnpm install
          pnpm store prune

      - name: Build application
        run: pnpm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore pnpm cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: npm install -g pnpm@latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run type check
        run: pnpm run type-check

      - name: Run linter
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm test
          
  deploy-qa:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Restore pnpm cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
  
      - name: Install pnpm
        run: npm install -g pnpm@latest
  
      - name: Install SWA CLI
        run: npm install -g @azure/static-web-apps-cli
  
      - name: Deploy to QA
        env:
          SWA_TOKEN: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
        run: |
          echo "Déploiement vers l'environnement de QA"
          swa deploy --env qa -d $SWA_TOKEN -a ./dist
  
  deploy-prod:
    needs: deploy-qa
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # Déployer sur prod uniquement lors d'un déclenchement manuel
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Restore pnpm cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-
  
      - name: Install pnpm
        run: npm install -g pnpm@latest
  
      - name: Install SWA CLI
        run: npm install -g @azure/static-web-apps-cli
  
      - name: Deploy to Prod
        env:
          SWA_TOKEN: ${{ secrets.SWA_DEPLOYMENT_TOKEN }}
        run: |
          echo "Déploiement vers l'environnement de production"
          swa deploy --env production -d $SWA_TOKEN -a ./dist
